# Check docs for default config
# Reference: https://getzola.org/documentation/getting-started/configuration/

base_url = "www.bevydioxus.com"
title = "bevy_dioxus"
description = "Write cross-platform application with React-like declarative UI framework and scalable ECS architecture all in Rust."
build_search_index = true

[markdown]
highlight_code = true
external_links_target_blank = true
